CREATE DATABASE MiniBiz;
USE MiniBiz;

CREATE TABLE RAW_MAT_INVENTORY(
MATERIAL_ID varchar(20) PRIMARY KEY,
MATERIAL_NAME VARCHAR(20),
QUANTITY INT,
UNIT_OF_MES VARCHAR(20),
SUPPLIER_ID INT,
LAST_UPDATED DATE
);

CREATE TABLE FinishedGoodsInventory (
    PRODUCT_ID varchar(20) PRIMARY KEY ,
    PRODUCT_NAME VARCHAR(100),
    QUANTITY INT,
    UNIT_PRICE DECIMAL(10,2),
    LAST_UPDATED DATE
);

CREATE TABLE CUSTOMERS(
CUSTOMER_ID varchar(20) PRIMARY KEY,
CUSTOMER_NAME varchar(20),
EMAIL varchar(50),
PHONE VARCHAR(13),
ADDRESS varchar(100)
);

CREATE TABLE ORDERS(
ORDER_ID varchar(20) PRIMARY KEY,
CUSTOMER_ID varchar(20),
STATUS varchar(3),
ORD_AMOUNT DECIMAL(10,2),
foreign key (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE OrderDetails (
    ORD_DETAIL_ID VARCHAR(20) PRIMARY KEY ,
    ORDER_ID VARCHAR(20),
    PRODUCT_ID varchar(20),
    QUANTITY INT,
    PRICE DECIMAL(10,2),
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES FinishedGoodsInventory(PRODUCT_ID)
);

CREATE TABLE Sales (
    SALE_ID varchar(20) PRIMARY KEY ,
    ORDER_ID VARCHAR(20),
    SALES_DATE DATE,
    TOTAL_AMT DECIMAL(10,2),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);
